#ifndef COMMAND_H
#define COMMAND_H

#define COMMAND_TRANSFER_INIT   0x10
#define COMMAND_TRANSFER_END    0x11
#define COMMAND_TRANSFER_END_R  0x12
#define COMMAND_TRANSFER_CHECKP 0x13
#define COMMAND_TRANSFER_CHECKF 0x14

#define COMMAND_INTERACT_GO     0x80
#define COMMAND_INTERACT_END    0x81
#define COMMAND_INTERACT_GET    0x82
#define COMMAND_INTERACT_SET    0x83
#define COMMAND_INTERACT_SET_W  0x84

#endif